package com.maiyatang.tokyo.community.mapper;

import com.maiyatang.tokyo.community.model.TucaoText;
import com.maiyatang.tokyo.community.model.TucaoTextExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TucaoTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOCAO_TEXT
     *
     * @mbg.generated Fri Mar 20 15:43:03 JST 2020
     */
    long countByExample(TucaoTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOCAO_TEXT
     *
     * @mbg.generated Fri Mar 20 15:43:03 JST 2020
     */
    int deleteByExample(TucaoTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOCAO_TEXT
     *
     * @mbg.generated Fri Mar 20 15:43:03 JST 2020
     */
    int deleteByPrimaryKey(Integer textId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOCAO_TEXT
     *
     * @mbg.generated Fri Mar 20 15:43:03 JST 2020
     */
    int insert(TucaoText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOCAO_TEXT
     *
     * @mbg.generated Fri Mar 20 15:43:03 JST 2020
     */
    int insertSelective(TucaoText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOCAO_TEXT
     *
     * @mbg.generated Fri Mar 20 15:43:03 JST 2020
     */
    List<TucaoText> selectByExampleWithBLOBsWithRowbounds(TucaoTextExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOCAO_TEXT
     *
     * @mbg.generated Fri Mar 20 15:43:03 JST 2020
     */
    List<TucaoText> selectByExampleWithBLOBs(TucaoTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOCAO_TEXT
     *
     * @mbg.generated Fri Mar 20 15:43:03 JST 2020
     */
    List<TucaoText> selectByExampleWithRowbounds(TucaoTextExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOCAO_TEXT
     *
     * @mbg.generated Fri Mar 20 15:43:03 JST 2020
     */
    List<TucaoText> selectByExample(TucaoTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOCAO_TEXT
     *
     * @mbg.generated Fri Mar 20 15:43:03 JST 2020
     */
    TucaoText selectByPrimaryKey(Integer textId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOCAO_TEXT
     *
     * @mbg.generated Fri Mar 20 15:43:03 JST 2020
     */
    int updateByExampleSelective(@Param("record") TucaoText record, @Param("example") TucaoTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOCAO_TEXT
     *
     * @mbg.generated Fri Mar 20 15:43:03 JST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") TucaoText record, @Param("example") TucaoTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOCAO_TEXT
     *
     * @mbg.generated Fri Mar 20 15:43:03 JST 2020
     */
    int updateByExample(@Param("record") TucaoText record, @Param("example") TucaoTextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOCAO_TEXT
     *
     * @mbg.generated Fri Mar 20 15:43:03 JST 2020
     */
    int updateByPrimaryKeySelective(TucaoText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOCAO_TEXT
     *
     * @mbg.generated Fri Mar 20 15:43:03 JST 2020
     */
    int updateByPrimaryKeyWithBLOBs(TucaoText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOCAO_TEXT
     *
     * @mbg.generated Fri Mar 20 15:43:03 JST 2020
     */
    int updateByPrimaryKey(TucaoText record);
}