package com.maiyatang.tokyo.community.model;

public class TucaoText {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOCAO_TEXT.TEXT_ID
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    private Integer textId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOCAO_TEXT.CREATOR
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOCAO_TEXT.TITLE
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOCAO_TEXT.TAG
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOCAO_TEXT.VIEW_COUNT
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOCAO_TEXT.LIKE_COUNT
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOCAO_TEXT.COMMENT_COUNT
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOCAO_TEXT.CREATE_TIME
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOCAO_TEXT.MODIFIED_TIME
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    private Long modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TOCAO_TEXT.DESCRIPTION
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOCAO_TEXT.TEXT_ID
     *
     * @return the value of TOCAO_TEXT.TEXT_ID
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public Integer getTextId() {
        return textId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOCAO_TEXT.TEXT_ID
     *
     * @param textId the value for TOCAO_TEXT.TEXT_ID
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public void setTextId(Integer textId) {
        this.textId = textId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOCAO_TEXT.CREATOR
     *
     * @return the value of TOCAO_TEXT.CREATOR
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOCAO_TEXT.CREATOR
     *
     * @param creator the value for TOCAO_TEXT.CREATOR
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOCAO_TEXT.TITLE
     *
     * @return the value of TOCAO_TEXT.TITLE
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOCAO_TEXT.TITLE
     *
     * @param title the value for TOCAO_TEXT.TITLE
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOCAO_TEXT.TAG
     *
     * @return the value of TOCAO_TEXT.TAG
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOCAO_TEXT.TAG
     *
     * @param tag the value for TOCAO_TEXT.TAG
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOCAO_TEXT.VIEW_COUNT
     *
     * @return the value of TOCAO_TEXT.VIEW_COUNT
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOCAO_TEXT.VIEW_COUNT
     *
     * @param viewCount the value for TOCAO_TEXT.VIEW_COUNT
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOCAO_TEXT.LIKE_COUNT
     *
     * @return the value of TOCAO_TEXT.LIKE_COUNT
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOCAO_TEXT.LIKE_COUNT
     *
     * @param likeCount the value for TOCAO_TEXT.LIKE_COUNT
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOCAO_TEXT.COMMENT_COUNT
     *
     * @return the value of TOCAO_TEXT.COMMENT_COUNT
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOCAO_TEXT.COMMENT_COUNT
     *
     * @param commentCount the value for TOCAO_TEXT.COMMENT_COUNT
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOCAO_TEXT.CREATE_TIME
     *
     * @return the value of TOCAO_TEXT.CREATE_TIME
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOCAO_TEXT.CREATE_TIME
     *
     * @param createTime the value for TOCAO_TEXT.CREATE_TIME
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOCAO_TEXT.MODIFIED_TIME
     *
     * @return the value of TOCAO_TEXT.MODIFIED_TIME
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public Long getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOCAO_TEXT.MODIFIED_TIME
     *
     * @param modifiedTime the value for TOCAO_TEXT.MODIFIED_TIME
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public void setModifiedTime(Long modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TOCAO_TEXT.DESCRIPTION
     *
     * @return the value of TOCAO_TEXT.DESCRIPTION
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TOCAO_TEXT.DESCRIPTION
     *
     * @param description the value for TOCAO_TEXT.DESCRIPTION
     *
     * @mbg.generated Wed Mar 18 12:42:16 JST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}