CREATE TABLE USER(
    "ID" INT AUTO_INCREMENT PRIMARY KEY NOT NULL ,
    "NAME" VARCHAR(50),
    "ACCOUNT_ID" VARCHAR(100),
    "TOKEN" CHAR(36),
    "CREATE_TIME" BIGINT,
    "MODIFIED_TIME" BIGINT,
    "AVATAR_URL" VARCHAR(200)
);

